/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netgrok.application;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JLabel;
import org.netgrok.components.Devices;
import org.netgrok.components.Networks;
import org.netgrok.runtime.Netgrok;

/**
 *
 * @author x87175
 */
public class ClickableGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClickableGUI
     */
    public ClickableGUI(Netgrok netgrok) {
        this.netgrok = netgrok;
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        setUndecorated(true);
        initComponents();
        functionLabel.setText("WHAT IS NETGROK?");
        functionTextArea.setText("NetGrok is a network tool that monitors network traffic and displays a functional view of the network.");
        outputTextArea.setText("In order to fully enjoy the NetGrok experience, it will help to connect to the NetGrok Wifi network. However, before you do, "
                + "it is important you understand certain rules.\n\nBy connecting to the NetGrok WiFi, you consent to monitoring, allowing NetGrok to monitor your network traffic only "
                + "while you are connected to its wifi. After leaving the wifi network, your network traffic will be deleted from the NetGrok database after five minutes.\n\nSSID: "
                + "NetGrokWiFi\nPassword: iconsenttomonitoring\n\n");
        outputLabel.setText("PROJECT'S DAY");
        outputTextArea.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        navBarPanel = new javax.swing.JPanel();
        websitesLabel = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        devicesLabel = new javax.swing.JLabel();
        networksLabel = new javax.swing.JLabel();
        minimizeButton1 = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        separatorPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        functionTextArea = new javax.swing.JTextArea();
        functionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout mainWindowLayout = new javax.swing.GroupLayout(mainWindow.getContentPane());
        mainWindow.getContentPane().setLayout(mainWindowLayout);
        mainWindowLayout.setHorizontalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainWindowLayout.setVerticalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NETGROK");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        closeButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(102, 102, 102));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.setIconTextGap(0);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindow(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        navBarPanel.setBackground(new java.awt.Color(0, 0, 0));

        websitesLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 60)); // NOI18N
        websitesLabel.setForeground(new java.awt.Color(102, 102, 102));
        websitesLabel.setText("WEBSITES");
        websitesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        websitesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getWebsites(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        homeLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 60)); // NOI18N
        homeLabel2.setForeground(new java.awt.Color(102, 102, 102));
        homeLabel2.setText("HOME");
        homeLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        homeLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goHome(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        devicesLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 60)); // NOI18N
        devicesLabel.setForeground(new java.awt.Color(102, 102, 102));
        devicesLabel.setText("DEVICES");
        devicesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        devicesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getDevices(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        networksLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 60)); // NOI18N
        networksLabel.setForeground(new java.awt.Color(102, 102, 102));
        networksLabel.setText("NETWORKS");
        networksLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        networksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getNetworks(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout navBarPanelLayout = new javax.swing.GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel2)
                .addGap(18, 18, 18)
                .addComponent(devicesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(networksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(websitesLabel)
                .addGap(228, 228, 228))
        );
        navBarPanelLayout.setVerticalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(homeLabel2)
                .addComponent(devicesLabel)
                .addComponent(networksLabel)
                .addComponent(websitesLabel))
        );

        minimizeButton1.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        minimizeButton1.setForeground(new java.awt.Color(102, 102, 102));
        minimizeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeButton1.setText("_");
        minimizeButton1.setIconTextGap(0);
        minimizeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindow(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMouseExited(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(102, 102, 102));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("NETGROK");
        homeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        separatorPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout separatorPanelLayout = new javax.swing.GroupLayout(separatorPanel);
        separatorPanel.setLayout(separatorPanelLayout);
        separatorPanelLayout.setHorizontalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separatorPanelLayout.setVerticalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        functionTextArea.setEditable(false);
        functionTextArea.setBackground(new java.awt.Color(0, 0, 0));
        functionTextArea.setColumns(20);
        functionTextArea.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        functionTextArea.setForeground(new java.awt.Color(102, 102, 102));
        functionTextArea.setLineWrap(true);
        functionTextArea.setRows(5);
        functionTextArea.setText("This menu will allow the user to view all the devices on the network. The NetGrok system will try it's best to figure out the name of the device - for example, \"x12345's iPad\". If not, NetGrok will identify the device by it's manufacturer - for example, \"Samsung\". Underneath each device will be all the websites NetGrok could see that you went to. Don't worry if you don't see your exact traffic in the output. The internet is really confusing and NetGrok is still trying to figure out how it works. If you have any questions, feel free to ask a NetGrok team member.");
        functionTextArea.setWrapStyleWord(true);
        functionTextArea.setAutoscrolls(false);
        functionTextArea.setBorder(null);
        jScrollPane2.setViewportView(functionTextArea);

        functionLabel.setBackground(new java.awt.Color(0, 0, 0));
        functionLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 48)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(102, 102, 102));
        functionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        functionLabel.setText("FUNCTION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(functionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(functionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        outputLabel.setBackground(new java.awt.Color(0, 0, 0));
        outputLabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 48)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(102, 102, 102));
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputLabel.setText("OUTPUT (Press 'DEVICES' to refresh)");

        outputTextArea.setEditable(false);
        outputTextArea.setBackground(new java.awt.Color(0, 0, 0));
        outputTextArea.setColumns(20);
        outputTextArea.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        outputTextArea.setForeground(new java.awt.Color(102, 102, 102));
        outputTextArea.setLineWrap(true);
        outputTextArea.setRows(5);
        outputTextArea.setText("Device information will show up here.");
        outputTextArea.setWrapStyleWord(true);
        outputTextArea.setAutoscrolls(false);
        outputTextArea.setBorder(null);
        jScrollPane3.setViewportView(outputTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void closeWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindow
        // TODO add your handling code here:
        dispatchEvent(new WindowEvent(mainWindow, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeWindow

    private void linkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseEntered
        // TODO add your handling code here:
        JLabel cur = (JLabel) evt.getSource();
        cur.setForeground(Color.WHITE);
    }//GEN-LAST:event_linkMouseEntered

    private void linkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseExited
        // TODO add your handling code here:
        JLabel cur = (JLabel) evt.getSource();
        cur.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_linkMouseExited

    private void minimizeWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindow
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeWindow

    private void getDevices(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getDevices
        // TODO add your handling code here:
        Devices devices = netgrok.getDevices();
        outputLabel.setText("OUTPUT (Press 'DEVICES' to refresh)");
        functionLabel.setText("FUNCTION");
        functionTextArea.setText("This menu will allow the user to view all the devices on the network. "
                + "The NetGrok system will try it's best to figure out the name of the device - for example, "
                + "\"x12345's iPad\". If not, NetGrok will identify the device by it's manufacturer - for "
                + "example, \"Samsung\". Underneath each device will be all the websites NetGrok could see that "
                + "you went to. Don't worry if you don't see your exact traffic in the output. The internet is "
                + "really confusing and NetGrok is still trying to figure out how it works. If you have any "
                + "questions, feel free to ask a NetGrok team member.");
        outputTextArea.setText(devices.toString());
        outputTextArea.setCaretPosition(0);
    }//GEN-LAST:event_getDevices

    private void getNetworks(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getNetworks
        // TODO add your handling code here:
        Networks networks = netgrok.getNetworks();
        outputLabel.setText("OUTPUT (Press 'NETWORKS' to refresh)");
        functionLabel.setText("FUNCTION");
        functionTextArea.setText("This menu will allow the user to view all the external networks that this network "
                + "has communicated with - for example, somebody on this network communicated with Snapchat, and another "
                + "communicated with Fox News, so the output will show connections to those websites. Netgrok follows a special "
                + "algorithm to figure out what actual websites "
                + "a user intended to visit. Don't worry if you don't see your exact traffic in the output. The internet is "
                + "really confusing and NetGrok is still trying to figure out how it works. If you have any "
                + "questions, feel free to ask a NetGrok team member.");
        outputTextArea.setText(networks.printSimple());
        outputTextArea.setCaretPosition(0);
    }//GEN-LAST:event_getNetworks

    private void getWebsites(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getWebsites
        // TODO add your handling code here:
        String websites = netgrok.getWebsites();
        outputLabel.setText("OUTPUT (Press 'WEBSITES' to refresh)");
        functionLabel.setText("FUNCTION");
        functionTextArea.setText("This menu is similar to the \"NETWORKS\" menu in that it will allow the user to view all communications "
                + "this network has seen. However, this menu differs in that it will show you all the communications NetGrok thought you explicitly "
                + "connected to - the user typed \"cnn.com\" into their address bar - and the underlying connections that happen, even when the user "
                + "isn't making explicit connections. NetGrok will not be able to map explicit connections to implicit connections. Instead, it will simply"
                + "divide all communications between explicit and implicit connections.");
        outputTextArea.setText(websites);
        outputTextArea.setCaretPosition(0);
    }//GEN-LAST:event_getWebsites

    private void goHome(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goHome
        // TODO add your handling code here:
        functionLabel.setText("PROJECT'S DAY");
        functionTextArea.setText("In order to fully enjoy the NetGrok experience, it will help to connect to the NetGrok Wifi network. However, before you do, "
                + "it is important you understand certain rules.\n\nBy connecting to the NetGrok WiFi, you consent to monitoring, allowing NetGrok to monitor your network traffic only "
                + "while you are connected to its wifi. After leaving the wifi network, your network traffic will be deleted from the NetGrok database after five minutes.\n\nSSID: "
                + "NetGrokWiFi\nPassword: iconsenttomonitoring\n\n");
        outputLabel.setText("WHAT IS NETGROK?");
        outputTextArea.setText("");
        outputTextArea.setCaretPosition(0);
    }//GEN-LAST:event_goHome

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClickableGUI(netgrok).setVisible(true);
            }
        });
    }
    
    private final Netgrok netgrok;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel devicesLabel;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JTextArea functionTextArea;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFrame mainWindow;
    private javax.swing.JLabel minimizeButton1;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JLabel networksLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JPanel separatorPanel;
    private javax.swing.JLabel websitesLabel;
    // End of variables declaration//GEN-END:variables
}
